services:
  frontend:
    build:
      context: ./FrontendService
    container_name: frontend_service
    ports:
      - "8050:8050"

  backend:
    build:
      context: ./BackendService
    container_name: backend_service
    ports:
      - "8000:8000"

  ml_service:
    image: python:3.9
    container_name: ml_service
    working_dir: /app
    volumes:
      - ./MlService:/app
    command: ["bash", "-c", "pip install -r requirements.txt && python ml_model.py"]

  data_service:
    image: ubuntu:20.04
    container_name: data_container
    volumes:
      - ./DataService/dataset:/data # Dataset
    command: [ "tail", "-f", "/dev/null" ]


  psql_database:
    build:
      context: ./DBService
    container_name: psql_db_container
    volumes:
      - psql_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  psql_volume:

# To run services individually and force build: docker compose up --build <service_name>