from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from . import models
from . import schemas
from .db import SessionLocal


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


router = APIRouter()
DATA_DIR = "/mnt/data/images"


# NOTE:
## FastAPI treats /route/ and /route as different!
## For consistency, use trailing slash when defining collections (e.g. /users/)
## Don't use training slash when defining individual entities (e.g. /users/{user_id})


@router.get("/users/", response_model=list[schemas.UserResponse])
async def list_users(db: Session = Depends(get_db)):
    users = db.query(models.User).all()
    return [schemas.UserResponse.model_validate(user)
            for user in users]

@router.get("/users/{user_id}", response_model=schemas.UserResponse)
async def get_user_by_id(user_id: int,
                         db: Session = Depends(get_db)):
    db_user = db.get(models.User, user_id)
    if db_user is None:
        raise HTTPException(status_code=404, detail="User not found")
    return schemas.UserResponse.model_validate(db_user)


@router.post("/users/", response_model=schemas.UserResponse)
async def create_user(user: schemas.UserCreate,
                      db: Session = Depends(get_db)):
    # TODO: id is integer and autoincrements, later refactor to uuid
    db_user = models.User(**user.model_dump())
    db.add(db_user)
    db.commit()
    db.refresh(db_user)  # load autogenerated fields, if any
    return schemas.UserResponse.model_validate(db_user)


@router.get("/races/", response_model = list[schemas.RaceResponse])
async def list_races(db: Session = Depends(get_db)):
    races = db.query(models.Race).all()
    return [schemas.RaceResponse.model_validate(race)
            for race in races]

@router.get("/races/{race_id}", response_model=schemas.RaceResponse)
async def get_race_by_id(race_id: int,
                         db: Session = Depends(get_db)):
    db_race = db.get(models.Race, race_id)
    if db_race is None:
        raise HTTPException(status_code=404, detail="Race not found")
    return schemas.RaceResponse.model_validate(db_race)


@router.get("/races/{race_id}/bibs/{bib_number}/images/")
async def list_race_images_with_bib():
    pass


@router.post("/races/", response_model=schemas.RaceResponse)
async def create_race(race: schemas.RaceCreate,
                      db: Session = Depends(get_db)):
    # TODO: id is integer and autoincrements, later refactor to uuid
    db_race = models.Race(**race.model_dump())
    db.add(db_race)
    db.commit()
    db.refresh(db_race)  # load autogenerated fields, if any
    return schemas.RaceResponse.model_validate(db_race)


@router.get("/registrations/", response_model=list[schemas.RegistrationResponse])
async def list_registrations(db: Session = Depends(get_db)):
    registrations = db.query(models.UserRace).all()
    return [schemas.RegistrationResponse.model_validate(registration)
            for registration in registrations]


@router.get("/registrations/{user_id}/{race_id}", response_model=schemas.RegistrationResponse)
async def get_registration_by_ids(user_id: int,
                                  race_id: int,
                                  db: Session = Depends(get_db)):
    # TODO: user_id and race_id should be explicitly passed in request body?
    #       Maybe we need to look into session manager (user_id from login, race_id from UI element)
    db_registration = db.get(models.UserRace, (user_id, race_id))
    if db_registration is None:
        raise HTTPException(status_code=404, detail="Registration not found")
    return schemas.RegistrationResponse.model_validate(db_registration)


@router.post("/registrations/", response_model=schemas.RegistrationResponse)
async def register_user_to_race(registration: schemas.RegistrationCreate,
                                db: Session = Depends(get_db)):
    # TODO: id is integer and autoincrements, later refactor to uuid
    db_registration = models.UserRace(**registration.model_dump())
    db.add(db_registration)
    db.commit()
    db.refresh(db_registration)  # load autogenerated fields, if any
    return schemas.RegistrationResponse.model_validate(db_registration)


@router.get("/images/{image_id}")
async def get_image_metadata_by_id():
    pass


@router.get("/images/{image_id}/bibs/")
async def list_bibs_for_image_by_id():
    pass


@router.post("/images/")
async def upload_image():
    pass


@router.get("/image-bibs/")
async def list_image_bib_links():
    pass


@router.post("/image-bibs/")
async def link_image_to_race_and_bib():
    pass
