from uuid import uuid4
from random import randint
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from .db import SessionLocal
from . import models
from . import schemas

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

router = APIRouter()
DATA_DIR = "/mnt/data/images"

# NOTE:
## FastAPI treats /route/ and /route as different!
## For consistency, use trailing slash when defining collections (e.g. /users/)
## Don't use training slash when defining individual entities (e.g. /users/{user_id})


@router.get("/users/")
async def list_users(db: Session = Depends(get_db)):
    return db.query(models.User).all()

@router.get("/users/{user_id}")
async def get_user_by_id():
    pass

@router.post("/users/")
async def create_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    # TODO: id is integer and autoincrements, later refactor to uuid
    db_user = models.User(**user.model_dump())
    db.add(db_user)
    db.commit()
    db.refresh(db_user)  # load autogenerated fields, if any
    return schemas.UserResponse.model_validate(db_user)

@router.get("/races/")
async def list_races(db: Session = Depends(get_db)):
    return db.query(models.Race).all()

@router.get("/races/{race_id}")
async def get_race_by_id():
    pass

@router.get("/races/{race_id}/bibs/{bib_number}/images/")
async def list_race_images_with_bib():
    pass

@router.post("/races/")
async def create_race(race: schemas.RaceCreate, db: Session = Depends(get_db)):
    # TODO: id is integer and autoincrements, later refactor to uuid
    db_race = models.Race(**race.model_dump())
    print(db_race.id, db_race.name, db_race.date)
    db.add(db_race)
    db.commit()
    db.refresh(db_race)  # load autogenerated fields, if any
    return schemas.RaceResponse.model_validate(db_race)


@router.get("/registrations/")
async def list_registrations():
    pass

@router.get("/registrations/{user_id}/{race_id}")
async def get_registration_by_ids():
    pass

@router.post("/registrations/")
async def register_user_to_race():
    pass

@router.get("/images/{image_id}")
async def get_image_metadata_by_id():
    pass

@router.get("/images/{image_id}/bibs/")
async def list_bibs_for_image_by_id():
    pass

@router.post("/images/")
async def upload_image():
    pass

@router.get("/image-bibs/")
async def list_image_bib_links():
    pass

@router.post("/image-bibs/")
async def link_image_to_race_and_bib():
    pass

