from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from . import models
from . import schemas
from .db import SessionLocal


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


router = APIRouter()
DATA_DIR = "/mnt/data/images"


# NOTE:
## FastAPI treats /route/ and /route as different!
## For consistency, use trailing slash when defining collections (e.g. /users/)
## Don't use training slash when defining individual entities (e.g. /users/{user_id})


@router.get("/users/")
async def list_users(db: Session = Depends(get_db),
                     response_model=list[schemas.UserResponse]):
    users = db.query(models.User).all()
    return [schemas.UserResponse.model_Validate(user)
            for user in users]

@router.get("/users/{user_id}")
async def get_user_by_id(user_id: int,
                         db: Session = Depends(get_db),
                         response_model=schemas.UserResponse):
    db_user = db.get(models.User, user_id)
    if db_user is None:
        raise HTTPException(status_code=404, detail="User not found")
    return schemas.UserResponse.model_validate(db_user)


@router.post("/users/")
async def create_user(user: schemas.UserCreate,
                      db: Session = Depends(get_db),
                      response_model=schemas.UserResponse):
    # TODO: id is integer and autoincrements, later refactor to uuid
    db_user = models.User(**user.model_dump())
    db.add(db_user)
    db.commit()
    db.refresh(db_user)  # load autogenerated fields, if any
    return schemas.UserResponse.model_validate(db_user)


@router.get("/races/")
async def list_races(db: Session = Depends(get_db),
                     response_model = list[schemas.UserResponse]):
    races = db.query(models.Race).all()
    return [schemas.RaceResponse.model_Validate(race)
            for race in races]

@router.get("/races/{race_id}")
async def get_race_by_id():
    pass


@router.get("/races/{race_id}/bibs/{bib_number}/images/")
async def list_race_images_with_bib():
    pass


@router.post("/races/")
async def create_race(race: schemas.RaceCreate,
                      db: Session = Depends(get_db),
                      response_model=schemas.RaceResponse):
    # TODO: id is integer and autoincrements, later refactor to uuid
    db_race = models.Race(**race.model_dump())
    db.add(db_race)
    db.commit()
    db.refresh(db_race)  # load autogenerated fields, if any
    return schemas.RaceResponse.model_validate(db_race)


@router.get("/registrations/")
async def list_registrations():
    pass


@router.get("/registrations/{user_id}/{race_id}")
async def get_registration_by_ids():
    pass


@router.post("/registrations/")
async def register_user_to_race():
    pass


@router.get("/images/{image_id}")
async def get_image_metadata_by_id():
    pass


@router.get("/images/{image_id}/bibs/")
async def list_bibs_for_image_by_id():
    pass


@router.post("/images/")
async def upload_image():
    pass


@router.get("/image-bibs/")
async def list_image_bib_links():
    pass


@router.post("/image-bibs/")
async def link_image_to_race_and_bib():
    pass
