import os
import IPython
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import sessionmaker, declarative_base
from pathlib import Path


Base = declarative_base()
class Image(Base):
    __tablename__ = 'images'

    id = Column(Integer, primary_key=True, index=True)  # id is auto-generated by PostgreSQL
    image_path = Column(String, nullable=False)  # image_path is the column we want to insert
